create database wordleAndresX2
go
use wordleAndresX2



create table palabras(

	ID INT identity(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(5) NOT NULL,

)


create table jugadores(

	ID INT identity(1,1) PRIMARY KEY,
	NICK VARCHAR(50) NOT NULL UNIQUE,

)


create table AparicionesJug(

	IDPALABRA INT,
	IDJUGADOR INT,
	NUMAPARICIONES INT NOT NULL,
	CONSTRAINT FKApariciones_Palabra FOREIGN KEY (IDPALABRA)
	REFERENCES palabras(ID),

	CONSTRAINT FKApariciones_Jugadores FOREIGN KEY (IDJUGADOR)
	REFERENCES jugadores(ID),

	PRIMARY KEY (IDPALABRA,IDJUGADOR)
)

create table partida(

	ID INT identity(1,1) PRIMARY KEY,
	IDJUGADOR INT NOT NULL,
	IDPALABRA INT NOT NULL,
	FECHA DATE NOT NULL,

	CONSTRAINT FKPartida_Palabra FOREIGN KEY (IDPALABRA)
	REFERENCES palabras(ID),

	
)

create table intentos(

	IDPARTIDA INT,
	IDINTENTO INT,
	CODIF VARCHAR(5) NOT NULL,
	PALABRA_INTENTADA VARCHAR(5) NOT NULL,
	CONSTRAINT FKIntentos_Partida FOREIGN KEY (IDPARTIDA)
	REFERENCES partida(ID),


	PRIMARY KEY(IDPARTIDA,IDINTENTO)
)

